# See https://supabase.com/docs/guides/local-development/cli/config

project_id = "elearning"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
# port = 54329
# pool_mode = "transaction"
# default_pool_size = 20
# max_client_conn = 100

# [db.vault]
# secret_key = "env(SECRET_VALUE)"

[db.migrations]
enabled = true
schema_paths = ["./migrations"]

[db.seed]
enabled = false
# sql_paths = ["./seeds/*.sql"]

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost:5000"
openai_api_key = "env(OPENAI_API_KEY)"

# [inbucket]
# enabled = true
# port = 54324
# smtp_port = 54325
# pop3_port = 54326
# admin_email = "admin@email.com"
# sender_name = "Admin"

[storage]
enabled = true
file_size_limit = "50MiB"

# [storage.buckets.assets]
# public = true
# file_size_limit = "10MiB"
# allowed_mime_types = [
#   "image/png",
#   "image/jpeg",
#   "image/webp",
#   "image/avif",
#   "image/svg+xml",
#   "video/mp4",
#   "video/webm",
#   "video/ogg",
# ]
# objects_path = "./assets"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits_symbols"

[auth.rate_limit]
email_sent = 2
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30

# [auth.captcha]
# enabled = true
# provider = "hcaptcha"
# secret = ""

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

# [auth.email.smtp]
# enabled = true
# host = "smtp.sendgrid.net"
# port = 587
# user = "apikey"
# pass = "env(SENDGRID_API_KEY)"
# admin_email = "admin@email.com"
# sender_name = "Admin"

# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
enable_signup = false
enable_confirmations = false

[edge_runtime]
enabled = false

[analytics]
enabled = true
port = 54327
backend = "postgres"
